### ISSUE TITLE
Podspec is wrongly attributed

### ISSUE THREAD

**Issue by jessesquires** [Criptext/Monkey-UI-iOS#4]
Hey @GianniCarlo !

It looks like you've mistakenly published this under my name. 

See comments at: https://github.com/CocoaPods/Specs/commit/cd74fea7c0c4ed34c50839ede218ecbf460010b0

**Comment by jessesquires** [comment]
Steps to fix:
1. `pod trunk delete MonkeyKit-UI 7.3.5`
2. update `homepage`, `authors`, and `social_media_url` in the spec.
3. `git tag -a 7.3.6 -m "7.3.6"`
4. push new pod to trunk

Thanks again for helping with this! 😄

**Comment by GianniCarlo** [comment]
all fixed! @jessesquires sorry about that

**Comment by jessesquires** [comment]
Thanks so much @GianniCarlo !

**Comment by jessesquires** [comment]
Oops. It looks like there's also a 7.3.4 spec that needs to be removed too.

https://github.com/CocoaPods/Specs/blob/master/Specs/MonkeyKit-UI/7.3.4/MonkeyKit-UI.podspec.json

**Comment by GianniCarlo** [comment]
done! @jessesquires again sorry for the trouble

**Comment by jessesquires** [comment]
Thanks!

![](https://media.giphy.com/media/10LKovKon8DENq/giphy.gif)
